" Name:         Arcana
" Version:      1.3.0
" Description:  Arcana, a semantically themed dark colour scheme based on an extended kanagwa palatte.
" Author:       bashful_strix <19427075+bashful-strix@users.noreply.github.com>
" Maintainer:   bashful_strix <19427075+bashful-strix@users.noreply.github.com>
" License:      Vim License (see `:help license`)
" Last Change:  2026 Mar 16

" Generated by Colortemplate v2.2.3

set background=dark

hi clear
let g:colors_name = 'arcana'

let s:t_Co = has('gui_running') ? -1 : get(g:, 'arcana_t_Co', get(g:, 't_Co', exists('&t_Co') ? +&t_Co : 0))
let s:italics = has('gui_running') || has('nvim') || (&t_ZH != '' && &t_ZH != '[7m' && !has('win32'))

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#0d0c0c', '#c34043', '#76946a', '#c0a36e', '#7e9cd8', '#957fb8', '#6a9589', '#c8c093', '#727169', '#e82424', '#98bb6c', '#e6c384', '#7fb4ca', '#938aa9', '#7aa89f', '#dcd7ba']
endif
if has('nvim')
  let g:terminal_color_0 = '#0d0c0c'
  let g:terminal_color_1 = '#c34043'
  let g:terminal_color_2 = '#76946a'
  let g:terminal_color_3 = '#c0a36e'
  let g:terminal_color_4 = '#7e9cd8'
  let g:terminal_color_5 = '#957fb8'
  let g:terminal_color_6 = '#6a9589'
  let g:terminal_color_7 = '#c8c093'
  let g:terminal_color_8 = '#727169'
  let g:terminal_color_9 = '#e82424'
  let g:terminal_color_10 = '#98bb6c'
  let g:terminal_color_11 = '#e6c384'
  let g:terminal_color_12 = '#7fb4ca'
  let g:terminal_color_13 = '#938aa9'
  let g:terminal_color_14 = '#7aa89f'
  let g:terminal_color_15 = '#dcd7ba'
endif
if get(g:, 'arcana_transp_bg', 1)
  hi Normal guifg=#c8c093 guibg=NONE gui=NONE cterm=NONE
  hi Terminal guifg=#c8c093 guibg=NONE gui=NONE cterm=NONE
else
  hi Normal guifg=#c8c093 guibg=#181616 gui=NONE cterm=NONE
  hi Terminal guifg=#c8c093 guibg=#181616 gui=NONE cterm=NONE
endif
hi ColorColumn guifg=NONE guibg=#282727 gui=NONE cterm=NONE
hi Conceal guifg=#87a987 guibg=#282727 gui=bold cterm=bold
hi Cursor guifg=#181616 guibg=#dcd7ba gui=NONE cterm=NONE
hi! link lCursor Cursor
hi! link CursorIM Cursor
hi! link CursorColumn Cursor
hi CursorLine guifg=NONE guibg=#393836 gui=NONE cterm=NONE
hi Directory guifg=#7e9cd8 guibg=NONE gui=NONE cterm=NONE
hi DiffAdd guifg=NONE guibg=#2b3328 gui=NONE cterm=NONE
hi DiffChange guifg=NONE guibg=#252535 gui=NONE cterm=NONE
hi DiffDelete guifg=#c34043 guibg=#43242b gui=NONE cterm=NONE
hi DiffText guifg=NONE guibg=#49443c gui=NONE cterm=NONE
hi EndOfBuffer guifg=#1f1f28 guibg=NONE gui=NONE cterm=NONE
hi ErrorMsg guifg=#e82424 guibg=NONE gui=NONE cterm=NONE
hi VertSplit guifg=#7a8382 guibg=NONE gui=NONE cterm=NONE
hi Folded guifg=#dcd7ba guibg=NONE gui=bold cterm=bold
hi FoldColumn guifg=#625e5a guibg=#282727 gui=NONE cterm=NONE
hi SignColumn guifg=#938aa9 guibg=#282727 gui=NONE cterm=NONE
hi IncSearch guifg=#223249 guibg=#ff9e3b gui=NONE cterm=NONE
hi LineNr guifg=#7a8382 guibg=#282727 gui=NONE cterm=NONE
hi! link LineNrAbove LineNr
hi! link LineNrBelow LineNr
hi CursorLineNr guifg=#ff9e3b guibg=#282727 gui=bold cterm=bold
hi! link CursorLineFold FoldColumn
hi! link CursorLineSign SignColumn
hi MatchParen guifg=#ff5d62 guibg=NONE gui=bold,underline cterm=bold,underline
hi! link MessageWindow WarningMsg
hi ModeMsg guifg=#ff9e3b guibg=NONE gui=bold cterm=bold
hi MoreMsg guifg=#658594 guibg=NONE gui=NONE cterm=NONE
hi NonText guifg=#625e5a guibg=NONE gui=NONE cterm=NONE
hi Pmenu guifg=NONE guibg=#223249 gui=NONE cterm=NONE
hi PmenuSel guifg=NONE guibg=#2d4f67 gui=NONE cterm=NONE
hi PmenuKind guifg=NONE guibg=#43436c gui=NONE cterm=NONE
hi PmenuKindSel guifg=NONE guibg=#54546d gui=NONE cterm=NONE
hi PmenuExtra guifg=NONE guibg=#363646 gui=NONE cterm=NONE
hi PmenuExtraSel guifg=NONE guibg=#545464 gui=NONE cterm=NONE
hi PmenuSbar guifg=NONE guibg=#697287 gui=NONE cterm=NONE
hi PmenuThumb guifg=NONE guibg=#8992a7 gui=NONE cterm=NONE
hi PmenuMatch guifg=#dca561 guibg=NONE gui=underline cterm=underline
hi PmenuMatchSel guifg=#e6c384 guibg=NONE gui=underline cterm=underline
hi! link PopupSelected PmenuSel
hi! link PopupNotification WarningMsg
hi! link Question MoreMsg
hi QuickFixLine guifg=NONE guibg=#2a2a37 gui=NONE cterm=NONE
hi Search guifg=#dcd7ba guibg=#2d4f67 gui=NONE cterm=NONE
hi CurSearch guifg=#181616 guibg=#dca561 gui=bold cterm=bold
hi SpecialKey guifg=#e98a00 guibg=NONE gui=NONE cterm=NONE
hi SpellBad guifg=NONE guibg=NONE guisp=#e82424 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi SpellCap guifg=NONE guibg=NONE guisp=#ff9e3b gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi SpellLocal guifg=NONE guibg=NONE guisp=#ff9e3b gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi SpellRare guifg=NONE guibg=NONE guisp=#ff9e3b gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
hi StatusLine guifg=#c8c093 guibg=#393836 gui=underline cterm=underline
hi StatusLineNC guifg=#7a8382 guibg=#282727 gui=underline cterm=underline
hi StatusLineTerm guifg=#c8c093 guibg=#0d0c0c gui=reverse cterm=reverse
hi StatusLineTermNC guifg=#7a8382 guibg=#0d0c0c gui=reverse cterm=reverse
hi TabLine guifg=#7a8382 guibg=#0d0c0c gui=underline cterm=underline
hi TabLineFill guifg=NONE guibg=#181616 gui=underline cterm=underline
hi TabLineSel guifg=#c8c093 guibg=#282727 gui=underline cterm=underline
hi Title guifg=#7e9cd8 guibg=NONE gui=bold cterm=bold
hi Visual guifg=NONE guibg=#223249 gui=NONE cterm=NONE
hi! link VisualNOS Visual
hi WarningMsg guifg=#ff9e3b guibg=NONE gui=NONE cterm=NONE
hi! link WildMenu Pmenu
hi debugBreakpoint guifg=#7fb4ca guibg=#282727 gui=NONE cterm=NONE
hi debugPC guifg=NONE guibg=#43242b gui=NONE cterm=NONE
hi Comment guifg=#716e61 guibg=NONE gui=italic cterm=italic
hi Constant guifg=#ffa066 guibg=NONE gui=NONE cterm=NONE
hi String guifg=#98bb6c guibg=NONE gui=NONE cterm=NONE
hi Character guifg=#76946a guibg=NONE gui=NONE cterm=NONE
hi Number guifg=#d27e99 guibg=NONE gui=NONE cterm=NONE
hi Boolean guifg=#ff9e3b guibg=NONE gui=bold cterm=bold
hi! link Float Number
hi Identifier guifg=#e6c384 guibg=NONE gui=NONE cterm=NONE
hi Function guifg=#dca561 guibg=NONE gui=NONE cterm=NONE
hi Statement guifg=#d7474b guibg=NONE gui=NONE cterm=NONE
hi Conditional guifg=#c84053 guibg=NONE gui=NONE cterm=NONE
hi! link Repeat Conditional
hi! link Label Conditional
hi Operator guifg=#cc6d00 guibg=NONE gui=NONE cterm=NONE
hi Keyword guifg=#c4746e guibg=NONE gui=NONE cterm=NONE
hi Exception guifg=#e46876 guibg=NONE gui=NONE cterm=NONE
hi PreProc guifg=#b35b79 guibg=NONE gui=NONE cterm=NONE
hi Include guifg=#697287 guibg=NONE gui=NONE cterm=NONE
hi Define guifg=#a292a3 guibg=NONE gui=NONE cterm=NONE
hi Macro guifg=#766b90 guibg=NONE gui=NONE cterm=NONE
hi PreCondit guifg=#b6927b guibg=NONE gui=NONE cterm=NONE
hi Type guifg=#7aa89f guibg=NONE gui=italic cterm=italic
hi StorageClass guifg=#c34043 guibg=NONE gui=NONE cterm=NONE
hi Structure guifg=#5a7785 guibg=NONE gui=NONE cterm=NONE
hi! link Typedef Type
hi Special guifg=#7aa880 guibg=NONE gui=NONE cterm=NONE
hi SpecialChar guifg=#4e8ca2 guibg=NONE gui=NONE cterm=NONE
hi Tag guifg=#6caf95 guibg=NONE gui=NONE cterm=NONE
hi Delimiter guifg=#597b75 guibg=NONE gui=NONE cterm=NONE
hi SpecialComment guifg=#737c73 guibg=NONE gui=italic cterm=italic
hi Debug guifg=#957fb8 guibg=NONE gui=NONE cterm=NONE
hi Underlined guifg=#7fb4ca guibg=NONE gui=underline cterm=underline
hi! link Ignore NonText
hi Error guifg=#e82424 guibg=NONE gui=NONE cterm=NONE
hi Todo guifg=#223249 guibg=#658594 gui=bold cterm=bold
hi! link Added DiffAdd
hi! link Changed DiffChange
hi! link Removed DiffDelete
hi ToolbarLine guifg=NONE guibg=#1f1f28 gui=NONE cterm=NONE
hi ToolbarButton guifg=#dcd7ba guibg=#1f1f28 gui=bold cterm=bold
hi DiagnosticError guifg=#c34043 guibg=NONE gui=NONE cterm=NONE
hi DiagnosticWarn guifg=#c0a36e guibg=NONE gui=NONE cterm=NONE
hi DiagnosticInfo guifg=#7e9cd8 guibg=NONE gui=NONE cterm=NONE
hi DiagnosticHint guifg=#6a9589 guibg=NONE gui=NONE cterm=NONE
hi DiagnosticUnderlineError guifg=NONE guibg=NONE guisp=#c34043 gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
hi DiagnosticUnderlineWarn guifg=NONE guibg=NONE guisp=#c0a36e gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
hi DiagnosticUnderlineInfo guifg=NONE guibg=NONE guisp=#7e9cd8 gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
hi DiagnosticUnderlineHint guifg=NONE guibg=NONE guisp=#6a9589 gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
hi DiagnosticVirtualTextError guifg=#83444b guibg=NONE gui=NONE cterm=NONE
hi DiagnosticVirtualTextWarn guifg=#79643c guibg=NONE gui=NONE cterm=NONE
hi DiagnosticVirtualTextInfo guifg=#455575 guibg=NONE gui=NONE cterm=NONE
hi DiagnosticVirtualTextHint guifg=#2a6569 guibg=NONE gui=NONE cterm=NONE
hi ArcBlack guifg=#0d0c0c guibg=NONE gui=NONE cterm=NONE
hi ArcRed guifg=#c34043 guibg=NONE gui=NONE cterm=NONE
hi ArcGreen guifg=#76946a guibg=NONE gui=NONE cterm=NONE
hi ArcYellow guifg=#c0a36e guibg=NONE gui=NONE cterm=NONE
hi ArcBlue guifg=#7e9cd8 guibg=NONE gui=NONE cterm=NONE
hi ArcMagenta guifg=#957fb8 guibg=NONE gui=NONE cterm=NONE
hi ArcCyan guifg=#6a9589 guibg=NONE gui=NONE cterm=NONE
hi ArcWhite guifg=#c8c093 guibg=NONE gui=NONE cterm=NONE
hi ArcBrightBlack guifg=#727169 guibg=NONE gui=NONE cterm=NONE
hi ArcBrightRed guifg=#e82424 guibg=NONE gui=NONE cterm=NONE
hi ArcBrightGreen guifg=#98bb6c guibg=NONE gui=NONE cterm=NONE
hi ArcBrightYellow guifg=#e6c384 guibg=NONE gui=NONE cterm=NONE
hi ArcBrightBlue guifg=#7fb4ca guibg=NONE gui=NONE cterm=NONE
hi ArcBrightMagenta guifg=#938aa9 guibg=NONE gui=NONE cterm=NONE
hi ArcBrightCyan guifg=#7aa89f guibg=NONE gui=NONE cterm=NONE
hi ArcBrightWhite guifg=#dcd7ba guibg=NONE gui=NONE cterm=NONE
hi ArcBlackItalic guifg=#0d0c0c guibg=NONE gui=italic cterm=italic
hi ArcRedItalic guifg=#c34043 guibg=NONE gui=italic cterm=italic
hi ArcGreenItalic guifg=#76946a guibg=NONE gui=italic cterm=italic
hi ArcYellowItalic guifg=#c0a36e guibg=NONE gui=italic cterm=italic
hi ArcBlueItalic guifg=#7e9cd8 guibg=NONE gui=italic cterm=italic
hi ArcMagentaItalic guifg=#957fb8 guibg=NONE gui=italic cterm=italic
hi ArcCyanItalic guifg=#6a9589 guibg=NONE gui=italic cterm=italic
hi ArcWhiteItalic guifg=#c8c093 guibg=NONE gui=italic cterm=italic
hi ArcBrightBlackItalic guifg=#727169 guibg=NONE gui=italic cterm=italic
hi ArcBrightRedItalic guifg=#e82424 guibg=NONE gui=italic cterm=italic
hi ArcBrightGreenItalic guifg=#98bb6c guibg=NONE gui=italic cterm=italic
hi ArcBrightYellowItalic guifg=#e6c384 guibg=NONE gui=italic cterm=italic
hi ArcBrightBlueItalic guifg=#7fb4ca guibg=NONE gui=italic cterm=italic
hi ArcBrightMagentaItalic guifg=#938aa9 guibg=NONE gui=italic cterm=italic
hi ArcBrightCyanItalic guifg=#7aa89f guibg=NONE gui=italic cterm=italic
hi ArcBrightWhiteItalic guifg=#dcd7ba guibg=NONE gui=italic cterm=italic
if !s:italics
  hi Comment gui=NONE cterm=NONE
  hi Type gui=NONE cterm=NONE
  hi SpecialComment gui=NONE cterm=NONE
  hi ArcBlackItalic gui=NONE cterm=NONE
  hi ArcRedItalic gui=NONE cterm=NONE
  hi ArcGreenItalic gui=NONE cterm=NONE
  hi ArcYellowItalic gui=NONE cterm=NONE
  hi ArcBlueItalic gui=NONE cterm=NONE
  hi ArcMagentaItalic gui=NONE cterm=NONE
  hi ArcCyanItalic gui=NONE cterm=NONE
  hi ArcWhiteItalic gui=NONE cterm=NONE
  hi ArcBrightBlackItalic gui=NONE cterm=NONE
  hi ArcBrightRedItalic gui=NONE cterm=NONE
  hi ArcBrightGreenItalic gui=NONE cterm=NONE
  hi ArcBrightYellowItalic gui=NONE cterm=NONE
  hi ArcBrightBlueItalic gui=NONE cterm=NONE
  hi ArcBrightMagentaItalic gui=NONE cterm=NONE
  hi ArcBrightCyanItalic gui=NONE cterm=NONE
  hi ArcBrightWhiteItalic gui=NONE cterm=NONE
endif
if get(g:, 'arcana_extend_ts', has('nvim'))
  hi! link @punctuation.delimiter SpecialKey
  hi! link @constant.builtin Boolean
  hi! link @property Normal
  hi! link @field Normal
  hi! link @variable.member @field
  hi! link @variable Identifier
  hi! link @namespace Statement
  hi! link @module @namespace
  hi! link @tag.delimiter Label
  hi! link @conditional Conditional
  hi! link @keyword.conditional @conditional
  hi! link @keyword.repeat Repeat
  hi! link @keyword.operator Operator
  hi! link @keyword.return Operator
  hi! link @punctuation.special Operator
  hi! link @exception Exception
  hi! link @keyword.exception @exception
  hi! link @include Include
  hi! link @keyword.import @include
  hi! link @parameter Define
  hi! link @variable.parameter @parameter
  hi! link @tag.attribute Define
  hi! link @constant.macro PreProc
  hi! link @variable.builtin PreProc
  hi! link @function.builtin PreCondit
  hi! link @function.macro PreCondit
  hi! link @keyword.directive Macro
  hi! link @keyword.coroutine StorageClass
  hi! link @keyword.modifier StorageClass
  hi! link @tag.builtin Structure
  hi! link @string.regexp Special
  hi! link @comment.documentation SpecialComment
  hi! link @keyword.debug Debug
endif

if s:t_Co >= 256
  if get(g:, 'arcana_transp_bg', 1)
    hi Normal ctermfg=144 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=144 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=144 ctermbg=233 cterm=NONE
    hi Terminal ctermfg=144 ctermbg=233 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=235 cterm=NONE
  hi Conceal ctermfg=108 ctermbg=235 cterm=bold
  hi Cursor ctermfg=233 ctermbg=187 cterm=NONE
  hi! link lCursor Cursor
  hi! link CursorIM Cursor
  hi! link CursorColumn Cursor
  hi CursorLine ctermfg=NONE ctermbg=237 cterm=NONE
  hi Directory ctermfg=111 ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=236 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=235 cterm=NONE
  hi DiffDelete ctermfg=131 ctermbg=236 cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=238 cterm=NONE
  hi EndOfBuffer ctermfg=234 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=196 ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=244 ctermbg=NONE cterm=NONE
  hi Folded ctermfg=187 ctermbg=NONE cterm=bold
  hi FoldColumn ctermfg=59 ctermbg=235 cterm=NONE
  hi SignColumn ctermfg=103 ctermbg=235 cterm=NONE
  hi IncSearch ctermfg=236 ctermbg=215 cterm=NONE
  hi LineNr ctermfg=244 ctermbg=235 cterm=NONE
  hi! link LineNrAbove LineNr
  hi! link LineNrBelow LineNr
  hi CursorLineNr ctermfg=215 ctermbg=235 cterm=bold
  hi! link CursorLineFold FoldColumn
  hi! link CursorLineSign SignColumn
  hi MatchParen ctermfg=203 ctermbg=NONE cterm=bold,underline
  hi! link MessageWindow WarningMsg
  hi ModeMsg ctermfg=215 ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=66 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=59 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=NONE ctermbg=236 cterm=NONE
  hi PmenuSel ctermfg=NONE ctermbg=24 cterm=NONE
  hi PmenuKind ctermfg=NONE ctermbg=60 cterm=NONE
  hi PmenuKindSel ctermfg=NONE ctermbg=60 cterm=NONE
  hi PmenuExtra ctermfg=NONE ctermbg=237 cterm=NONE
  hi PmenuExtraSel ctermfg=NONE ctermbg=240 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=243 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=103 cterm=NONE
  hi PmenuMatch ctermfg=179 ctermbg=NONE cterm=underline
  hi PmenuMatchSel ctermfg=222 ctermbg=NONE cterm=underline
  hi! link PopupSelected PmenuSel
  hi! link PopupNotification WarningMsg
  hi! link Question MoreMsg
  hi QuickFixLine ctermfg=NONE ctermbg=236 cterm=NONE
  hi Search ctermfg=187 ctermbg=24 cterm=NONE
  hi CurSearch ctermfg=233 ctermbg=179 cterm=bold
  hi SpecialKey ctermfg=172 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine ctermfg=144 ctermbg=237 cterm=underline
  hi StatusLineNC ctermfg=244 ctermbg=235 cterm=underline
  hi StatusLineTerm ctermfg=144 ctermbg=232 cterm=reverse
  hi StatusLineTermNC ctermfg=244 ctermbg=232 cterm=reverse
  hi TabLine ctermfg=244 ctermbg=232 cterm=underline
  hi TabLineFill ctermfg=NONE ctermbg=233 cterm=underline
  hi TabLineSel ctermfg=144 ctermbg=235 cterm=underline
  hi Title ctermfg=111 ctermbg=NONE cterm=bold
  hi Visual ctermfg=NONE ctermbg=236 cterm=NONE
  hi! link VisualNOS Visual
  hi WarningMsg ctermfg=215 ctermbg=NONE cterm=NONE
  hi! link WildMenu Pmenu
  hi debugBreakpoint ctermfg=74 ctermbg=235 cterm=NONE
  hi debugPC ctermfg=NONE ctermbg=236 cterm=NONE
  hi Comment ctermfg=242 ctermbg=NONE cterm=italic
  hi Constant ctermfg=216 ctermbg=NONE cterm=NONE
  hi String ctermfg=107 ctermbg=NONE cterm=NONE
  hi Character ctermfg=65 ctermbg=NONE cterm=NONE
  hi Number ctermfg=175 ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=215 ctermbg=NONE cterm=bold
  hi! link Float Number
  hi Identifier ctermfg=222 ctermbg=NONE cterm=NONE
  hi Function ctermfg=179 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=167 ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=161 ctermbg=NONE cterm=NONE
  hi! link Repeat Conditional
  hi! link Label Conditional
  hi Operator ctermfg=166 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=167 ctermbg=NONE cterm=NONE
  hi Exception ctermfg=167 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=132 ctermbg=NONE cterm=NONE
  hi Include ctermfg=243 ctermbg=NONE cterm=NONE
  hi Define ctermfg=139 ctermbg=NONE cterm=NONE
  hi Macro ctermfg=60 ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=137 ctermbg=NONE cterm=NONE
  hi Type ctermfg=109 ctermbg=NONE cterm=italic
  hi StorageClass ctermfg=131 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=66 ctermbg=NONE cterm=NONE
  hi! link Typedef Type
  hi Special ctermfg=108 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=31 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=72 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=66 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=243 ctermbg=NONE cterm=italic
  hi Debug ctermfg=104 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=74 ctermbg=NONE cterm=underline
  hi! link Ignore NonText
  hi Error ctermfg=196 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=236 ctermbg=66 cterm=bold
  hi! link Added DiffAdd
  hi! link Changed DiffChange
  hi! link Removed DiffDelete
  hi ToolbarLine ctermfg=NONE ctermbg=234 cterm=NONE
  hi ToolbarButton ctermfg=187 ctermbg=234 cterm=bold
  hi DiagnosticError ctermfg=131 ctermbg=NONE cterm=NONE
  hi DiagnosticWarn ctermfg=179 ctermbg=NONE cterm=NONE
  hi DiagnosticInfo ctermfg=111 ctermbg=NONE cterm=NONE
  hi DiagnosticHint ctermfg=66 ctermbg=NONE cterm=NONE
  hi DiagnosticUnderlineError ctermfg=NONE ctermbg=NONE cterm=underline
  hi DiagnosticUnderlineWarn ctermfg=NONE ctermbg=NONE cterm=underline
  hi DiagnosticUnderlineInfo ctermfg=NONE ctermbg=NONE cterm=underline
  hi DiagnosticUnderlineHint ctermfg=NONE ctermbg=NONE cterm=underline
  hi DiagnosticVirtualTextError ctermfg=95 ctermbg=NONE cterm=NONE
  hi DiagnosticVirtualTextWarn ctermfg=94 ctermbg=NONE cterm=NONE
  hi DiagnosticVirtualTextInfo ctermfg=60 ctermbg=NONE cterm=NONE
  hi DiagnosticVirtualTextHint ctermfg=23 ctermbg=NONE cterm=NONE
  hi ArcBlack ctermfg=232 ctermbg=NONE cterm=NONE
  hi ArcRed ctermfg=131 ctermbg=NONE cterm=NONE
  hi ArcGreen ctermfg=65 ctermbg=NONE cterm=NONE
  hi ArcYellow ctermfg=179 ctermbg=NONE cterm=NONE
  hi ArcBlue ctermfg=111 ctermbg=NONE cterm=NONE
  hi ArcMagenta ctermfg=104 ctermbg=NONE cterm=NONE
  hi ArcCyan ctermfg=66 ctermbg=NONE cterm=NONE
  hi ArcWhite ctermfg=144 ctermbg=NONE cterm=NONE
  hi ArcBrightBlack ctermfg=242 ctermbg=NONE cterm=NONE
  hi ArcBrightRed ctermfg=196 ctermbg=NONE cterm=NONE
  hi ArcBrightGreen ctermfg=107 ctermbg=NONE cterm=NONE
  hi ArcBrightYellow ctermfg=222 ctermbg=NONE cterm=NONE
  hi ArcBrightBlue ctermfg=74 ctermbg=NONE cterm=NONE
  hi ArcBrightMagenta ctermfg=103 ctermbg=NONE cterm=NONE
  hi ArcBrightCyan ctermfg=109 ctermbg=NONE cterm=NONE
  hi ArcBrightWhite ctermfg=187 ctermbg=NONE cterm=NONE
  hi ArcBlackItalic ctermfg=232 ctermbg=NONE cterm=italic
  hi ArcRedItalic ctermfg=131 ctermbg=NONE cterm=italic
  hi ArcGreenItalic ctermfg=65 ctermbg=NONE cterm=italic
  hi ArcYellowItalic ctermfg=179 ctermbg=NONE cterm=italic
  hi ArcBlueItalic ctermfg=111 ctermbg=NONE cterm=italic
  hi ArcMagentaItalic ctermfg=104 ctermbg=NONE cterm=italic
  hi ArcCyanItalic ctermfg=66 ctermbg=NONE cterm=italic
  hi ArcWhiteItalic ctermfg=144 ctermbg=NONE cterm=italic
  hi ArcBrightBlackItalic ctermfg=242 ctermbg=NONE cterm=italic
  hi ArcBrightRedItalic ctermfg=196 ctermbg=NONE cterm=italic
  hi ArcBrightGreenItalic ctermfg=107 ctermbg=NONE cterm=italic
  hi ArcBrightYellowItalic ctermfg=222 ctermbg=NONE cterm=italic
  hi ArcBrightBlueItalic ctermfg=74 ctermbg=NONE cterm=italic
  hi ArcBrightMagentaItalic ctermfg=103 ctermbg=NONE cterm=italic
  hi ArcBrightCyanItalic ctermfg=109 ctermbg=NONE cterm=italic
  hi ArcBrightWhiteItalic ctermfg=187 ctermbg=NONE cterm=italic
  if !s:italics
    hi Comment cterm=NONE
    hi Type cterm=NONE
    hi SpecialComment cterm=NONE
    hi ArcBlackItalic cterm=NONE
    hi ArcRedItalic cterm=NONE
    hi ArcGreenItalic cterm=NONE
    hi ArcYellowItalic cterm=NONE
    hi ArcBlueItalic cterm=NONE
    hi ArcMagentaItalic cterm=NONE
    hi ArcCyanItalic cterm=NONE
    hi ArcWhiteItalic cterm=NONE
    hi ArcBrightBlackItalic cterm=NONE
    hi ArcBrightRedItalic cterm=NONE
    hi ArcBrightGreenItalic cterm=NONE
    hi ArcBrightYellowItalic cterm=NONE
    hi ArcBrightBlueItalic cterm=NONE
    hi ArcBrightMagentaItalic cterm=NONE
    hi ArcBrightCyanItalic cterm=NONE
    hi ArcBrightWhiteItalic cterm=NONE
  endif
  if get(g:, 'arcana_extend_ts', has('nvim'))
    hi! link @punctuation.delimiter SpecialKey
    hi! link @constant.builtin Boolean
    hi! link @property Normal
    hi! link @field Normal
    hi! link @variable.member @field
    hi! link @variable Identifier
    hi! link @namespace Statement
    hi! link @module @namespace
    hi! link @tag.delimiter Label
    hi! link @conditional Conditional
    hi! link @keyword.conditional @conditional
    hi! link @keyword.repeat Repeat
    hi! link @keyword.operator Operator
    hi! link @keyword.return Operator
    hi! link @punctuation.special Operator
    hi! link @exception Exception
    hi! link @keyword.exception @exception
    hi! link @include Include
    hi! link @keyword.import @include
    hi! link @parameter Define
    hi! link @variable.parameter @parameter
    hi! link @tag.attribute Define
    hi! link @constant.macro PreProc
    hi! link @variable.builtin PreProc
    hi! link @function.builtin PreCondit
    hi! link @function.macro PreCondit
    hi! link @keyword.directive Macro
    hi! link @keyword.coroutine StorageClass
    hi! link @keyword.modifier StorageClass
    hi! link @tag.builtin Structure
    hi! link @string.regexp Special
    hi! link @comment.documentation SpecialComment
    hi! link @keyword.debug Debug
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: sumiInk0      #16161D           ~
" Color: sumiInk1      #181820           ~
" Color: sumiInk2      #1a1a22           ~
" Color: sumiInk3      #1f1f28           ~
" Color: sumiInk4      #2a2a37           ~
" Color: sumiInk5      #363646           ~
" Color: sumiInk6      #54546d           ~
" Color: waveBlue1     #223249           ~
" Color: waveBlue2     #2d4f67           ~
" Color: winterGreen   #2b3328           ~
" Color: winterYellow  #49443c           ~
" Color: winterRed     #43242b           ~
" Color: winterBlue    #252535           ~
" Color: autumnGreen   #76946a           ~
" Color: autumnRed     #c34043           ~
" Color: autumnYellow  #dca561           ~
" Color: senpouRed     #83444b           ~
" Color: senpouYellow  #79643c           ~
" Color: senpouBlue    #455575           ~
" Color: senpouAqua    #2a6569           ~
" Color: samuraiRed    #e82424           ~
" Color: roninYellow   #ff9e3b           ~
" Color: waveAqua1     #6a9589           ~
" Color: dragonBlue    #658594           ~
" Color: oldWhite      #c8c093           ~
" Color: fujiWhite     #dcd7ba           ~
" Color: fujiGray      #727169           ~
" Color: oniViolet     #957fb8           ~
" Color: oniViolet2    #B8B4D0           ~
" Color: oniViolet3    #c8a4d0           ~
" Color: crystalBlue   #7e9cd8           ~
" Color: springViolet1 #938aa9           ~
" Color: springViolet2 #9cabca           ~
" Color: springBlue    #7fb4ca           ~
" Color: lightBlue     #a3d4d5           ~
" Color: waveAqua2     #7aa89f           ~
" Color: waveAqua3     #68ad99           ~
" Color: waveAqua4     #7aa880           ~
" Color: waveAqua5     #6caf95           ~
" Color: springGreen   #98bb6c           ~
" Color: boatYellow1   #938056           ~
" Color: boatYellow2   #c0a36e           ~
" Color: boatYellow3   #b0834e           ~
" Color: carpYellow    #e6c384           ~
" Color: sakuraPink    #d27e99           ~
" Color: waveRed       #e46876           ~
" Color: peachRed      #ff5d62           ~
" Color: surimiOrange  #ffa066           ~
" Color: katanaGray    #717c7c           ~
" Color: dragonBlack0  #0d0c0c           ~
" Color: dragonBlack1  #12120f           ~
" Color: dragonBlack2  #1d1c19           ~
" Color: dragonBlack3  #181616           ~
" Color: dragonBlack4  #282727           ~
" Color: dragonBlack5  #393836           ~
" Color: dragonBlack6  #625e5a           ~
" Color: dragonWhite   #c5c9c5           ~
" Color: dragonGreen   #87a987           ~
" Color: dragonGreen2  #8a9a7b           ~
" Color: dragonPink    #a292a3           ~
" Color: dragonOrange  #b6927b           ~
" Color: dragonOrange2 #b98d7b           ~
" Color: dragonGray    #a6a69c           ~
" Color: dragonGray2   #9e9b93           ~
" Color: dragonGray3   #7a8382           ~
" Color: dragonBlue2   #8ba4b0           ~
" Color: dragonViolet  #8992a7           ~
" Color: dragonViolet2 #697287           ~
" Color: dragonRed     #c4746e           ~
" Color: dragonAqua    #8ea4a2           ~
" Color: dragonAsh     #737c73           ~
" Color: dragonTeal    #949fb5           ~
" Color: dragonTeal2   #B39F67           ~
" Color: dragonYellow  #c4b28a           ~
" Color: dragonYellow2 #a99c8b           ~
" Color: dragonYellow3 #8a9aa3           ~
" Color: lotusInk1     #545464           ~
" Color: lotusInk2     #43436c           ~
" Color: lotusGray     #dcd7ba           ~
" Color: lotusGray2    #716e61           ~
" Color: lotusGray3    #8a8980           ~
" Color: lotusWhite0   #d5cea3           ~
" Color: lotusWhite1   #dcd5ac           ~
" Color: lotusWhite2   #e5ddb0           ~
" Color: lotusWhite3   #f2ecbc           ~
" Color: lotusWhite4   #e7dba0           ~
" Color: lotusWhite5   #e4d794           ~
" Color: lotusViolet1  #a09cac           ~
" Color: lotusViolet2  #766b90           ~
" Color: lotusViolet3  #c9cbd1           ~
" Color: lotusViolet4  #624c83           ~
" Color: lotusBlue1    #c7d7e0           ~
" Color: lotusBlue2    #b5cbd2           ~
" Color: lotusBlue3    #9fb5c9           ~
" Color: lotusBlue4    #4d699b           ~
" Color: lotusBlue5    #5d57a3           ~
" Color: lotusGreen    #6f894e           ~
" Color: lotusGreen2   #6e915f           ~
" Color: lotusGreen3   #b7d0ae           ~
" Color: lotusPink     #b35b79           ~
" Color: lotusOrange   #cc6d00           ~
" Color: lotusOrange2  #e98a00           ~
" Color: lotusYellow   #77713f           ~
" Color: lotusYellow2  #836f4a           ~
" Color: lotusYellow3  #de9800           ~
" Color: lotusYellow4  #f9d791           ~
" Color: lotusRed      #c84053           ~
" Color: lotusRed2     #d7474b           ~
" Color: lotusRed3     #e82424           ~
" Color: lotusRed4     #d9a594           ~
" Color: lotusAqua     #597b75           ~
" Color: lotusAqua2    #5e857a           ~
" Color: lotusTeal1    #4e8ca2           ~
" Color: lotusTeal2    #6693bf           ~
" Color: lotusTeal3    #5a7785           ~
" Color: lotusCyan     #d7e3d8           ~
" Term colors:         dragonBlack0      autumnRed         autumnGreen
" Term colors:         boatYellow2       crystalBlue       oniViolet
" Term colors:         waveAqua1         oldWhite          fujiGray
" Term colors:         samuraiRed        springGreen       carpYellow
" Term colors:         springBlue        springViolet1     waveAqua2
" Term colors:         fujiWhite
" vim: et ts=8 sw=2 sts=2
